default:
	$(MAKE) -C optimized

full:
	$(MAKE) -C optimized
	$(MAKE) -C optimized_xaxis_soft
	$(MAKE) -C optimized_xaxis

clean:
	$(MAKE) -C optimized            clean
	$(MAKE) -C optimized_xaxis_soft clean
	$(MAKE) -C optimized_xaxis      clean
