#! /bin/sh

formats="$1"
[ "$formats"x = x ] && formats="SDF CFD"

version=`visit -version 2>&1|sed 's,.* \([0-9]*\).*,\1,'`

if [ "$version"x != x ]; then
  for fmt in $formats; do
    xml2info -clobber ${fmt}${version}.xml
    rm -f CMake* cmake* Makefile

    if [ $version -eq 1 ]; then
      xml2makefile -clobber ${fmt}${version}.xml
      if [ "`uname -s`"x = "Darwinx" -a "`uname -m`"x = "x86_64x" ]; then
        sed 's,\(^CXXFLAGS.*\),\1 -m32 -g\
CFLAGS=$(CFLAGSORIG) -m32 -g\
PY_CXXFLAGS=-I$(TOPDIR)/include/python,;s,\(^LDFLAGS.*\),\1 -m32,' Makefile > .Makefile.tmp
        \mv -f .Makefile.tmp Makefile
      fi
    else
      xml2cmake -clobber ${fmt}${version}.xml
      cmake -DCMAKE_BUILD_TYPE=Debug .
    fi

    make clean
    make
  done
else
  echo "Unable to build. Please add visit to your \$PATH"
fi

if [ "$fmt"x = "SDF"x ]; then
  mpicc -DPARALLEL -DSDF_DEBUG_ALL -g -o sdf2ascii sdf2ascii.c sdf_control.c \
      sdf_input.c sdf_input_cartesian.c sdf_input_point.c
fi
