#! /bin/sh

SDFDIR=../SDF_lib

clean=0
DBG=""

while getopts cdp name
do
   case $name in
      c) clean=1 ;;
      d) DBG="-g -O0" ;;
   esac
done

cd `dirname $0`/.

if [ $clean -eq 1 ] ; then
  rm -rf sdf2ascii sdf2ascii.dSYM
  #[ -r pybuild/files.txt ] && cat pybuild/files.txt | xargs rm
  rm -rf pybuild
fi
if [ $clean -le 1 ] ; then
  gcc -DSDF_DEBUG_ALL $DBG -I$SDFDIR -o sdf2ascii sdf2ascii.c \
      $SDFDIR/sdf_control.c $SDFDIR/sdf_input.c $SDFDIR/sdf_input_cartesian.c \
      $SDFDIR/sdf_input_point.c
  python setup.py build -b pybuild install --prefix= --user --record pybuild/files.txt
fi
