#! /bin/sh

SDFDIR=../SDF_lib
EXTDIR=../extension

clean=0
DBG=""
PYDBG=""

while getopts crdph name
do
   case $name in
      c) clean=2 ;;
      r) clean=1 ;;
      d) DBG="-g -O0"; PYDBG="-g" ;;
      h) cat <<EOF
build script options:
  -c: Clean up files. Do not build anything.
  -r: Rebuild. Clean up files and then build.
  -d: Build with debugging flags enabled.
EOF
         exit ;;
   esac
done

cd `dirname $0`/.

if [ $clean -ge 1 ] ; then
  rm -rf sdf2ascii sdf2ascii.dSYM
  [ -r pybuild/files.txt ] && cat pybuild/files.txt | xargs rm
  rm -rf pybuild
fi
if [ $clean -le 1 ] ; then
  gcc -DSDF_DEBUG_ALL $DBG -I$SDFDIR -o sdf2ascii sdf2ascii.c \
      $SDFDIR/sdf_control.c $SDFDIR/sdf_input.c $SDFDIR/sdf_input_cartesian.c \
      $SDFDIR/sdf_input_point.c $SDFDIR/sdf_input_station.c $SDFDIR/sdf_util.c
  gcc -DSDF_DEBUG_ALL $DBG -I$SDFDIR -I$EXTDIR -o sdffilter sdffilter.c \
      $SDFDIR/sdf_control.c $SDFDIR/sdf_input.c $SDFDIR/sdf_input_cartesian.c \
      $SDFDIR/sdf_input_point.c $SDFDIR/sdf_input_station.c $SDFDIR/sdf_util.c \
      $SDFDIR/sdf_extension_util.c $SDFDIR/sdf_derived.c -ldl
  CFLAGS="-Wno-unused-function $DBG" python setup.py build $PYDBG -b pybuild install --prefix= --user --record pybuild/files.txt
fi
