#! /bin/sh

SDFDIR=../SDF_lib

debug=0

if [ $debug -ne 0 ]; then
  DBG=""
else
  DBG="-g -O0"
fi

cd `dirname $0`/.

gcc -DSDF_DEBUG_ALL $DBG -I$SDFDIR -o sdf2ascii sdf2ascii.c \
    $SDFDIR/sdf_control.c $SDFDIR/sdf_input.c $SDFDIR/sdf_input_cartesian.c \
    $SDFDIR/sdf_input_point.c
python setup.py build -b pybuild install --user
