default:
	$(MAKE) -C lehe_x
	$(MAKE) -C cowan

full:
	$(MAKE) -C yee
	$(MAKE) -C lehe_x
	$(MAKE) -C pukhov
	$(MAKE) -C cowan

clean:
	$(MAKE) -C yee     clean
	$(MAKE) -C lehe_x  clean
	$(MAKE) -C pukhov  clean
	$(MAKE) -C cowan   clean
