/*****************************************************************************
*
* Copyright (c) 2000 - 2009, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-400124
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//                            avtCFDFileFormat.C                           //
// ************************************************************************* //

#include <avtCFDFileFormat.h>

#include <string>

#include <vtkFloatArray.h>
#include <vtkRectilinearGrid.h>
#include <vtkStructuredGrid.h>
#include <vtkUnstructuredGrid.h>

#include <avtDatabaseMetaData.h>

#include <DBOptionsAttributes.h>
#include <Expression.h>

#include <InvalidVariableException.h>
#include <InvalidDBTypeException.h>


using     std::string;


// ****************************************************************************
//  Method: avtCFDFileFormat constructor
//
//  Programmer: phsgbd -- generated by xml2avt
//  Creation:   Tue Aug 14 12:02:50 PDT 2007
//
// ****************************************************************************

avtCFDFileFormat::avtCFDFileFormat(const char *filename)
    : avtSTMDFileFormat(&filename, 1)
{
    debug1 << "avtCFDFileFormat::avtCFDFileFormat:" << filename << endl;
    if (!this->Handler.Open(filename))
        EXCEPTION1(InvalidDBTypeException, "Database is invalid");
}


// ****************************************************************************
//  Method: avtCFDFileFormat::FreeUpResources
//
//  Purpose:
//      When VisIt is done focusing on a particular timestep, it asks that
//      timestep to free up any resources (memory, file descriptors) that
//      it has associated with it.  This method is the mechanism for doing
//      that.
//
//  Programmer: phsgbd -- generated by xml2avt
//  Creation:   Tue Aug 14 12:02:50 PDT 2007
//
// ****************************************************************************

void
avtCFDFileFormat::FreeUpResources(void)
{
    debug1 << "avtCFDFileFormat::FreeUpResources" << endl;
    Handler.FreeUpResources();
}


// ****************************************************************************
//  Method: avtCFDFileFormat::PopulateDatabaseMetaData
//
//  Purpose:
//      This database meta-data object is like a table of contents for the
//      file.  By populating it, you are telling the rest of VisIt what
//      information it can request from you.
//
//  Programmer: phsgbd -- generated by xml2avt
//  Creation:   Tue Aug 14 12:02:50 PDT 2007
//
// ****************************************************************************

void
avtCFDFileFormat::PopulateDatabaseMetaData(avtDatabaseMetaData *md)
{
    debug1 << "avtCFDFileFormat::PopulateDatabaseMetaData" << endl;
    Handler.PopulateDatabaseMetaData(md);
}


// ****************************************************************************
//  Method: avtCFDFileFormat::GetMesh
//
//  Purpose:
//      Gets the mesh associated with this file.  The mesh is returned as a
//      derived type of vtkDataSet (ie vtkRectilinearGrid, vtkStructuredGrid,
//      vtkUnstructuredGrid, etc).
//
//  Arguments:
//      domain      The index of the domain.  If there are NDomains, this
//                  value is guaranteed to be between 0 and NDomains-1,
//                  regardless of block origin.
//      meshname    The name of the mesh of interest.  This can be ignored if
//                  there is only one mesh.
//
//  Programmer: phsgbd -- generated by xml2avt
//  Creation:   Tue Aug 14 12:02:50 PDT 2007
//
// ****************************************************************************

vtkDataSet *
avtCFDFileFormat::GetMesh(int domain, const char *meshname)
{
    debug1 << "avtCFDFileFormat::GetMesh:" << domain << "," << meshname << endl;
    vtkDataSet *Dat = Handler.GetMesh(domain, meshname);
    if (Dat) return Dat;
    EXCEPTION1(InvalidDBTypeException, "Database is invalid");
}


// ****************************************************************************
//  Method: avtCFDFileFormat::GetVar
//
//  Purpose:
//      Gets a scalar variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      domain     The index of the domain.  If there are NDomains, this
//                 value is guaranteed to be between 0 and NDomains-1,
//                 regardless of block origin.
//      varname    The name of the variable requested.
//
//  Programmer: phsgbd -- generated by xml2avt
//  Creation:   Tue Aug 14 12:02:50 PDT 2007
//
// ****************************************************************************

vtkDataArray *
avtCFDFileFormat::GetVar(int domain, const char *varname)
{
    debug1 << "avtCFDFileFormat::GetVar:" << domain << "," << varname << endl;
    return Handler.GetVar(domain, varname);
}


// ****************************************************************************
//  Method: avtCFDFileFormat::GetVectorVar
//
//  Purpose:
//      Gets a vector variable associated with this file.  Although VTK has
//      support for many different types, the best bet is vtkFloatArray, since
//      that is supported everywhere through VisIt.
//
//  Arguments:
//      domain     The index of the domain.  If there are NDomains, this
//                 value is guaranteed to be between 0 and NDomains-1,
//                 regardless of block origin.
//      varname    The name of the variable requested.
//
//  Programmer: phsgbd -- generated by xml2avt
//  Creation:   Tue Aug 14 12:02:50 PDT 2007
//
// ****************************************************************************

vtkDataArray *
avtCFDFileFormat::GetVectorVar(int domain, const char *varname)
{
    debug1 << "avtCFDFileFormat::GetVectorVar:" << domain << ","
           << varname << endl;
    return Handler.GetVectorVar(domain, varname);
}


// ****************************************************************************
//  Method: avtCFDFileFormat::GetCycleFromFilename
//
//  Purpose:
//      Gets the cycle number from the file name.
//
//  Arguments:
//      f     The file name for which to return a cyle number
//
//  Programmer: Keith Bennett
//  Creation:   Sat Apr 3, 2010
//
// ****************************************************************************

int
avtCFDFileFormat::GetCycleFromFilename(const char *f) const
{
    debug1 << "avtCFDFileFormat::GetCycleFromFilename:" << f << endl;
    return Handler.GetCycle();
}
