default:
	$(MAKE) -C optimized

full:
	$(MAKE) -C optimized
	$(MAKE) -C optimized_symm
	$(MAKE) -C optimized_xaxis

clean:
	$(MAKE) -C optimized       clean
	$(MAKE) -C optimized_symm  clean
	$(MAKE) -C optimized_xaxis clean
