default:
	$(MAKE) -C optimized

full:
	$(MAKE) -C lehe_custom
	$(MAKE) -C lehe_x
	$(MAKE) -C optimized

clean:
	$(MAKE) -C lehe_custom clean
	$(MAKE) -C lehe_x      clean
	$(MAKE) -C optimized   clean
